name: Deploy web
on:
  workflow_call:
    inputs:
      CONFIGURATION:
        required: true
        type: string
    secrets:
      WEB_DEPLOY:
        required: true
env:
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  DOTNET_VERSION: 6.0.x
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
        working-directory: src/Frontend
      - run: npm run build
        working-directory: src/Frontend
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: src/Backend/WebAPI/wwwroot
          retention-days: 1
  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: src/Backend/WebAPI/wwwroot
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet restore src/Backend/WebAPI/WebAPI.csproj
      - run: dotnet build src/Backend/WebAPI/WebAPI.csproj --configuration ${{ inputs.CONFIGURATION }} --no-restore
      - run: dotnet publish src/Backend/WebAPI/WebAPI.csproj --configuration ${{ inputs.CONFIGURATION }}  --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      - uses: azure/webapps-deploy@v2
        with:
          app-name: expense-adjustmenter
          publish-profile: ${{ secrets.WEB_DEPLOY }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
